In [55]:
import pandas as pd

In [56]:
df = pd.read_csv(r"C:\Users\Monay\Code\Machine Learning\Projects\intel-daily-stock-price-prediction\data\raw\intel-daily-stock-price-data-raw.csv")

In [57]:
df.head()

,Price,Open,High,Low,Close,Volume,Dividends
0,Ticker,INTC,INTC,INTC,INTC,INTC,INTC
1,Date,NaN,NaN,NaN,NaN,NaN,NaN
2,2021-04-01,58.86365707338173,59.01827255130448,57.826813255853125,58.709041595458984,31416300,0.0
3,2021-04-05,59.072845540812764,60.7008740638183,58.84546737177341,60.51897430419922,27947500,0.0
4,2021-04-06,60.082411414667426,60.555361941310586,59.38208963437075,59.627655029296875,28771400,0.0

In [58]:
df.tail()

,Price,Open,High,Low,Close,Volume,Dividends
1272,2026-04-23,66.0999984741211,68.27999877929688,65.41999816894531,66.77999877929688,155141800,0.0
1273,2026-04-24,82.19999694824219,85.22000122070312,79.62000274658203,82.54000091552734,281405200,0.0
1274,2026-04-27,83.66999816894531,87.0999984741211,82.61000061035156,84.98999786376953,178820200,0.0
1275,2026-04-28,81.27999877929688,84.58999633789062,80.80000305175781,84.5199966430664,147773500,0.0
1276,2026-04-29,86.13999938964844,94.94999694824219,85.87000274658203,94.75,235070900,0.0

In [59]:
df = df.drop([0, 1])
df

,Price,Open,High,Low,Close,Volume,Dividends
2,2021-04-01,58.86365707338173,59.01827255130448,57.826813255853125,58.709041595458984,31416300,0.0
3,2021-04-05,59.072845540812764,60.7008740638183,58.84546737177341,60.51897430419922,27947500,0.0
4,2021-04-06,60.082411414667426,60.555361941310586,59.38208963437075,59.627655029296875,28771400,0.0
5,2021-04-07,59.727695674536186,60.54625846946761,59.4457489659052,60.25521469116211,17793300,0.0
6,2021-04-08,60.910063555214876,61.20110732696513,60.355260281092384,60.982826232910156,22224200,0.0
...,...,...,...,...,...,...,...
1272,2026-04-23,66.0999984741211,68.27999877929688,65.41999816894531,66.77999877929688,155141800,0.0
1273,2026-04-24,82.19999694824219,85.22000122070312,79.62000274658203,82.54000091552734,281405200,0.0
1274,2026-04-27,83.66999816894531,87.0999984741211,82.61000061035156,84.98999786376953,178820200,0.0
1275,2026-04-28,81.27999877929688,84.58999633789062,80.80000305175781,84.5199966430664,147773500,0.0
1276,2026-04-29,86.13999938964844,94.94999694824219,85.87000274658203,94.75,235070900,0.0

In [60]:
df = df.rename(columns={"Price":"Date"})
df

,Date,Open,High,Low,Close,Volume,Dividends
2,2021-04-01,58.86365707338173,59.01827255130448,57.826813255853125,58.709041595458984,31416300,0.0
3,2021-04-05,59.072845540812764,60.7008740638183,58.84546737177341,60.51897430419922,27947500,0.0
4,2021-04-06,60.082411414667426,60.555361941310586,59.38208963437075,59.627655029296875,28771400,0.0
5,2021-04-07,59.727695674536186,60.54625846946761,59.4457489659052,60.25521469116211,17793300,0.0
6,2021-04-08,60.910063555214876,61.20110732696513,60.355260281092384,60.982826232910156,22224200,0.0
...,...,...,...,...,...,...,...
1272,2026-04-23,66.0999984741211,68.27999877929688,65.41999816894531,66.77999877929688,155141800,0.0
1273,2026-04-24,82.19999694824219,85.22000122070312,79.62000274658203,82.54000091552734,281405200,0.0
1274,2026-04-27,83.66999816894531,87.0999984741211,82.61000061035156,84.98999786376953,178820200,0.0
1275,2026-04-28,81.27999877929688,84.58999633789062,80.80000305175781,84.5199966430664,147773500,0.0
1276,2026-04-29,86.13999938964844,94.94999694824219,85.87000274658203,94.75,235070900,0.0

In [61]:
df.isna().sum()

Date         0
Open         0
High         0
Low          0
Close        0
Volume       0
Dividends    0
dtype: int64

In [62]:
df.notna().sum()

Date         1275
Open         1275
High         1275
Low          1275
Close        1275
Volume       1275
Dividends    1275
dtype: int64

In [63]:
df.duplicated().sum()

np.int64(0)

In [64]:
df["Date"] = pd.to_datetime(df["Date"])

In [65]:
numeric_cols = ["Open", "High", "Low", "Close", "Volume", "Dividends"]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col])

In [66]:
df = df.sort_values("Date")

In [67]:
df = df.reset_index(drop=True)

In [68]:
df.dtypes

Date         datetime64[us]
Open                float64
High                float64
Low                 float64
Close               float64
Volume                int64
Dividends           float64
dtype: object

In [69]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1275 entries, 0 to 1274
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       1275 non-null   datetime64[us]
 1   Open       1275 non-null   float64
 2   High       1275 non-null   float64
 3   Low        1275 non-null   float64
 4   Close      1275 non-null   float64
 5   Volume     1275 non-null   int64
 6   Dividends  1275 non-null   float64
dtypes: datetime64[us](1), float64(5), int64(1)
memory usage: 69.9 KB