In [136]:
import pandas as pd

In [153]:
df = pd.read_csv(r"C:\Users\norie\Documents\Machine Learning\Projects\intel-daily-stock-price-prediction\data\cleaned\intel-daily-stock-price-data-cleaned.csv")

In [154]:
df.head()

         Date       Open       High        Low      Close    Volume  Dividends
0  2021-04-01  58.863657  59.018273  57.826813  58.709042  31416300        0.0
1  2021-04-05  59.072846  60.700874  58.845467  60.518974  27947500        0.0
2  2021-04-06  60.082411  60.555362  59.382090  59.627655  28771400        0.0
3  2021-04-07  59.727696  60.546258  59.445749  60.255215  17793300        0.0
4  2021-04-08  60.910064  61.201107  60.355260  60.982826  22224200        0.0

In [155]:
df.tail()

,Date,Open,High,Low,Close,Volume,Dividends
1270,2026-04-23,66.099998,68.279999,65.419998,66.779999,155141800,0.0
1271,2026-04-24,82.199997,85.220001,79.620003,82.540001,281405200,0.0
1272,2026-04-27,83.669998,87.099998,82.610001,84.989998,178820200,0.0
1273,2026-04-28,81.279999,84.589996,80.800003,84.519997,147773500,0.0
1274,2026-04-29,86.139999,94.949997,85.870003,94.750000,235070900,0.0

In [156]:
df["MA5"] = df["Close"].rolling(window=5).mean()
df.head()

,Date,Open,High,Low,Close,Volume,Dividends,MA5
0,2021-04-01,58.863657,59.018273,57.826813,58.709042,31416300,0.0,NaN
1,2021-04-05,59.072846,60.700874,58.845467,60.518974,27947500,0.0,NaN
2,2021-04-06,60.082411,60.555362,59.382090,59.627655,28771400,0.0,NaN
3,2021-04-07,59.727696,60.546258,59.445749,60.255215,17793300,0.0,NaN
4,2021-04-08,60.910064,61.201107,60.355260,60.982826,22224200,0.0,60.018742

In [157]:
df["MA14"] = df["Close"].rolling(window=14).mean()
df.head()

,Date,Open,High,Low,Close,Volume,Dividends,MA5,MA14
0,2021-04-01,58.863657,59.018273,57.826813,58.709042,31416300,0.0,NaN,NaN
1,2021-04-05,59.072846,60.700874,58.845467,60.518974,27947500,0.0,NaN,NaN
2,2021-04-06,60.082411,60.555362,59.382090,59.627655,28771400,0.0,NaN,NaN
3,2021-04-07,59.727696,60.546258,59.445749,60.255215,17793300,0.0,NaN,NaN
4,2021-04-08,60.910064,61.201107,60.355260,60.982826,22224200,0.0,60.018742,NaN

In [158]:
df["Daily Return"] = df["Close"].pct_change()
df.head()

,Date,Open,High,Low,Close,Volume,Dividends,MA5,MA14,Daily Return
0,2021-04-01,58.863657,59.018273,57.826813,58.709042,31416300,0.0,NaN,NaN,NaN
1,2021-04-05,59.072846,60.700874,58.845467,60.518974,27947500,0.0,NaN,NaN,0.030829
2,2021-04-06,60.082411,60.555362,59.382090,59.627655,28771400,0.0,NaN,NaN,-0.014728
3,2021-04-07,59.727696,60.546258,59.445749,60.255215,17793300,0.0,NaN,NaN,0.010525
4,2021-04-08,60.910064,61.201107,60.355260,60.982826,22224200,0.0,60.018742,NaN,0.012075

In [159]:
# Price changes
delta = df["Close"].diff()

# Gains and losses
gain = delta.clip(lower=0)
loss = -delta.clip(upper=0)

# Average gain/loss
avg_gain = gain.rolling(window=14).mean()
avg_loss = loss.rolling(window=14).mean()

# Relative strength
rs = avg_gain / avg_loss

# RSI
df["RSI"] = 100 - (100 / (1 + rs))

df.head()

,Date,Open,High,Low,Close,Volume,Dividends,MA5,MA14,Daily Return,RSI
0,2021-04-01,58.863657,59.018273,57.826813,58.709042,31416300,0.0,NaN,NaN,NaN,NaN
1,2021-04-05,59.072846,60.700874,58.845467,60.518974,27947500,0.0,NaN,NaN,0.030829,NaN
2,2021-04-06,60.082411,60.555362,59.382090,59.627655,28771400,0.0,NaN,NaN,-0.014728,NaN
3,2021-04-07,59.727696,60.546258,59.445749,60.255215,17793300,0.0,NaN,NaN,0.010525,NaN
4,2021-04-08,60.910064,61.201107,60.355260,60.982826,22224200,0.0,60.018742,NaN,0.012075,NaN

In [160]:
# Moving average
ma20 = df["Close"].rolling(window=20).mean()

# Standard deviation
std20 = df["Close"].rolling(window=20).std()

# Upper and lower bands
upper = ma20 + (2 * std20)
lower = ma20 - (2 * std20)

# Bollinger Band Width
df["Bollinger Band Width"] = (upper - lower) / ma20

df.iloc[0:25]

,Date,Open,High,Low,Close,Volume,Dividends,MA5,MA14,Daily Return,RSI,Bollinger Band Width
0,2021-04-01,58.863657,59.018273,57.826813,58.709042,31416300,0.000,NaN,NaN,NaN,NaN,NaN
1,2021-04-05,59.072846,60.700874,58.845467,60.518974,27947500,0.000,NaN,NaN,0.030829,NaN,NaN
2,2021-04-06,60.082411,60.555362,59.382090,59.627655,28771400,0.000,NaN,NaN,-0.014728,NaN,NaN
3,2021-04-07,59.727696,60.546258,59.445749,60.255215,17793300,0.000,NaN,NaN,0.010525,NaN,NaN
4,2021-04-08,60.910064,61.201107,60.355260,60.982826,22224200,0.000,60.018742,NaN,0.012075,NaN,NaN
5,2021-04-09,60.755441,62.210659,60.600818,62.083328,27177100,0.000,60.693600,NaN,0.018046,NaN,NaN
6,2021-04-12,62.028756,62.292516,58.854559,59.491222,51266900,0.000,60.488049,NaN,-0.041752,NaN,NaN
7,2021-04-13,59.673130,59.691317,58.399811,59.318420,26822000,0.000,60.426202,NaN,-0.002905,NaN,NaN
8,2021-04-14,59.400264,59.463930,58.063283,58.381615,25768400,0.000,60.051482,NaN,-0.015793,NaN,NaN
9,2021-04-15,58.181525,59.318416,57.917765,59.136509,24927700,0.000,59.682219,NaN,0.012930,NaN,NaN
10,2021-04-16,59.418461,59.591263,58.727229,58.890942,24625500,0.000,59.043742,NaN,-0.004153,NaN,NaN
11,2021-04-19,58.845462,58.881844,57.362959,57.872288,23997700,0.000,58.719955,NaN,-0.017297,NaN,NaN
12,2021-04-20,57.881384,57.990525,56.762684,57.026443,19872100,0.000,58.261559,NaN,-0.014616,NaN,NaN
13,2021-04-21,57.108306,58.008722,56.662643,57.935963,24364200,0.000,58.172429,59.302174,0.015949,NaN,NaN
14,2021-04-22,57.617626,58.126954,56.644447,56.908207,38257600,0.000,57.726768,59.173543,-0.017740,43.408787,NaN
15,2021-04-23,53.806769,54.570760,52.660785,53.879532,77479500,0.000,56.724487,58.699297,-0.053220,27.689469,NaN
16,2021-04-26,53.752197,54.134194,53.170110,53.442963,39645900,0.000,55.838622,58.257534,-0.008103,28.562392,NaN
17,2021-04-27,53.261058,53.324724,52.542542,52.724445,38167700,0.000,54.978222,57.719622,-0.013445,24.060137,NaN
18,2021-04-28,52.315170,52.897258,51.978652,52.406120,30387400,0.000,53.872253,57.107000,-0.006038,19.600243,NaN
19,2021-04-29,52.642590,53.024584,52.269690,53.006393,23290600,0.000,53.091891,56.458647,0.011454,16.644387,0.206127
20,2021-04-30,52.397027,53.142827,51.905890,52.324265,30731800,0.000,52.780837,55.946722,-0.012869,19.362367,0.222169
21,2021-05-03,52.624407,52.642598,51.696704,52.078697,22281700,0.000,52.507984,55.429599,-0.004693,19.242655,0.231542
22,2021-05-04,51.733076,51.824026,50.759898,51.751266,35323600,0.000,52.313348,54.956002,-0.006287,20.293397,0.241925
23,2021-05-05,51.805842,52.115077,51.351086,51.705795,21001900,0.000,52.173283,54.425237,-0.000879,14.447361,0.246577
24,2021-05-06,51.813773,52.390296,51.475182,52.335388,25529300,0.348,52.039082,53.956983,0.012176,19.746366,0.240723

In [161]:
df["High-Low Range"] = df["High"] - df["Low"]
df.head()

,Date,Open,High,Low,Close,Volume,Dividends,MA5,MA14,Daily Return,RSI,Bollinger Band Width,High-Low Range
0,2021-04-01,58.863657,59.018273,57.826813,58.709042,31416300,0.0,NaN,NaN,NaN,NaN,NaN,1.191459
1,2021-04-05,59.072846,60.700874,58.845467,60.518974,27947500,0.0,NaN,NaN,0.030829,NaN,NaN,1.855407
2,2021-04-06,60.082411,60.555362,59.382090,59.627655,28771400,0.0,NaN,NaN,-0.014728,NaN,NaN,1.173272
3,2021-04-07,59.727696,60.546258,59.445749,60.255215,17793300,0.0,NaN,NaN,0.010525,NaN,NaN,1.100510
4,2021-04-08,60.910064,61.201107,60.355260,60.982826,22224200,0.0,60.018742,NaN,0.012075,NaN,NaN,0.845847

In [162]:
df["Relative Volume"] = (df["Volume"] / df["Volume"].rolling(20).mean())
df.head()

,Date,Open,High,Low,Close,Volume,Dividends,MA5,MA14,Daily Return,RSI,Bollinger Band Width,High-Low Range,Relative Volume
0,2021-04-01,58.863657,59.018273,57.826813,58.709042,31416300,0.0,NaN,NaN,NaN,NaN,NaN,1.191459,NaN
1,2021-04-05,59.072846,60.700874,58.845467,60.518974,27947500,0.0,NaN,NaN,0.030829,NaN,NaN,1.855407,NaN
2,2021-04-06,60.082411,60.555362,59.382090,59.627655,28771400,0.0,NaN,NaN,-0.014728,NaN,NaN,1.173272,NaN
3,2021-04-07,59.727696,60.546258,59.445749,60.255215,17793300,0.0,NaN,NaN,0.010525,NaN,NaN,1.100510,NaN
4,2021-04-08,60.910064,61.201107,60.355260,60.982826,22224200,0.0,60.018742,NaN,0.012075,NaN,NaN,0.845847,NaN

In [163]:
df["Target"] = df["Close"].pct_change().shift(-1)
df.head()

,Date,Open,High,Low,Close,Volume,Dividends,MA5,MA14,Daily Return,RSI,Bollinger Band Width,High-Low Range,Relative Volume,Target
0,2021-04-01,58.863657,59.018273,57.826813,58.709042,31416300,0.0,NaN,NaN,NaN,NaN,NaN,1.191459,NaN,0.030829
1,2021-04-05,59.072846,60.700874,58.845467,60.518974,27947500,0.0,NaN,NaN,0.030829,NaN,NaN,1.855407,NaN,-0.014728
2,2021-04-06,60.082411,60.555362,59.382090,59.627655,28771400,0.0,NaN,NaN,-0.014728,NaN,NaN,1.173272,NaN,0.010525
3,2021-04-07,59.727696,60.546258,59.445749,60.255215,17793300,0.0,NaN,NaN,0.010525,NaN,NaN,1.100510,NaN,0.012075
4,2021-04-08,60.910064,61.201107,60.355260,60.982826,22224200,0.0,60.018742,NaN,0.012075,NaN,NaN,0.845847,NaN,0.018046

In [164]:
df.tail()

,Date,Open,High,Low,Close,Volume,Dividends,MA5,MA14,Daily Return,RSI,Bollinger Band Width,High-Low Range,Relative Volume,Target
1270,2026-04-23,66.099998,68.279999,65.419998,66.779999,155141800,0.0,66.501999,62.977143,0.023135,80.688604,0.669407,2.860001,1.406796,0.235999
1271,2026-04-24,82.199997,85.220001,79.620003,82.540001,281405200,0.0,69.309999,65.245714,0.235999,87.737630,0.711292,5.599998,2.340977,0.029683
1272,2026-04-27,83.669998,87.099998,82.610001,84.989998,178820200,0.0,73.167999,67.537143,0.029683,87.830175,0.732354,4.489998,1.423169,-0.005530
1273,2026-04-28,81.279999,84.589996,80.800003,84.519997,147773500,0.0,76.819998,69.363571,-0.005530,84.713531,0.709069,3.789993,1.147237,0.121036
1274,2026-04-29,86.139999,94.949997,85.870003,94.750000,235070900,0.0,82.715999,71.722857,0.121036,87.288312,0.741362,9.079994,1.731046,NaN

In [165]:
df = df.drop(columns=["Open", "High", "Low", "Volume", "Dividends"])
df.head()

,Date,Close,MA5,MA14,Daily Return,RSI,Bollinger Band Width,High-Low Range,Relative Volume,Target
0,2021-04-01,58.709042,NaN,NaN,NaN,NaN,NaN,1.191459,NaN,0.030829
1,2021-04-05,60.518974,NaN,NaN,0.030829,NaN,NaN,1.855407,NaN,-0.014728
2,2021-04-06,59.627655,NaN,NaN,-0.014728,NaN,NaN,1.173272,NaN,0.010525
3,2021-04-07,60.255215,NaN,NaN,0.010525,NaN,NaN,1.100510,NaN,0.012075
4,2021-04-08,60.982826,60.018742,NaN,0.012075,NaN,NaN,0.845847,NaN,0.018046

In [166]:
del_rows = [x for x in range(0, 19)]
del_rows

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]

In [167]:
df = df.drop(del_rows)
df = df.drop(df.index[-1])
df

,Date,Close,MA5,MA14,Daily Return,RSI,Bollinger Band Width,High-Low Range,Relative Volume,Target
19,2021-04-29,53.006393,53.091891,56.458647,0.011454,16.644387,0.206127,0.754894,0.746251,-0.012869
20,2021-04-30,52.324265,52.780837,55.946722,-0.012869,19.362367,0.222169,1.236938,0.985754,-0.004693
21,2021-05-03,52.078697,52.507984,55.429599,-0.004693,19.242655,0.231542,0.945894,0.721263,-0.006287
22,2021-05-04,51.751266,52.313348,54.956002,-0.006287,20.293397,0.241925,1.064128,1.131433,-0.000879
23,2021-05-05,51.705795,52.173283,54.425237,-0.000879,14.447361,0.246577,0.763991,0.669262,0.012176
...,...,...,...,...,...,...,...,...,...,...
1269,2026-04-22,65.269997,66.845999,61.805714,-0.014941,81.277195,0.682210,3.789993,0.840505,0.023135
1270,2026-04-23,66.779999,66.501999,62.977143,0.023135,80.688604,0.669407,2.860001,1.406796,0.235999
1271,2026-04-24,82.540001,69.309999,65.245714,0.235999,87.737630,0.711292,5.599998,2.340977,0.029683
1272,2026-04-27,84.989998,73.167999,67.537143,0.029683,87.830175,0.732354,4.489998,1.423169,-0.005530
1273,2026-04-28,84.519997,76.819998,69.363571,-0.005530,84.713531,0.709069,3.789993,1.147237,0.121036

In [168]:
df.set_index('Date', inplace=True)
df

,Close,MA5,MA14,Daily Return,RSI,Bollinger Band Width,High-Low Range,Relative Volume,Target
Date,,,,,,,,,
2021-04-29,53.006393,53.091891,56.458647,0.011454,16.644387,0.206127,0.754894,0.746251,-0.012869
2021-04-30,52.324265,52.780837,55.946722,-0.012869,19.362367,0.222169,1.236938,0.985754,-0.004693
2021-05-03,52.078697,52.507984,55.429599,-0.004693,19.242655,0.231542,0.945894,0.721263,-0.006287
2021-05-04,51.751266,52.313348,54.956002,-0.006287,20.293397,0.241925,1.064128,1.131433,-0.000879
2021-05-05,51.705795,52.173283,54.425237,-0.000879,14.447361,0.246577,0.763991,0.669262,0.012176
...,...,...,...,...,...,...,...,...,...
2026-04-22,65.269997,66.845999,61.805714,-0.014941,81.277195,0.682210,3.789993,0.840505,0.023135
2026-04-23,66.779999,66.501999,62.977143,0.023135,80.688604,0.669407,2.860001,1.406796,0.235999
2026-04-24,82.540001,69.309999,65.245714,0.235999,87.737630,0.711292,5.599998,2.340977,0.029683
2026-04-27,84.989998,73.167999,67.537143,0.029683,87.830175,0.732354,4.489998,1.423169,-0.005530
2026-04-28,84.519997,76.819998,69.363571,-0.005530,84.713531,0.709069,3.789993,1.147237,0.121036